print(" Import NumPy as np")
import numpy as np

print("Create an array of 10 zeros ")
array = np.zeros(10)
print(array)
print("Create an array of 10 ones")
array = np.ones(10)
print(array)
print("Create an array of 10 fives")
array = np.ones(10) * 5
print(array)
array = np.zeros(10) + 5
print(array)
print("Create an array of the integers from 10 to 50")
array = np.arange(10, 51)
print(array)
print(" Create an array of all the even integers from 10 to 50")
array = np.arange(10, 51, 2)
print(array)
print("Use NumPy to generate a random number between 0 and 1")
array = np.arange(0, 9)
print(array.reshape(3, 3))
print("Create a 3x3 identity matrix")
array = np.eye(3, 3)
print(array)
print("Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution")
array = np.random.random(25)
print(array)
array = np.random.randn(25)
print(array)
print("Create the following matrix:")
array = np.arange(1, 101).reshape(10, 10) / 100
print(array)
print("Create an array of 20 linearly spaced points between 0 and 1:")
array = np.linspace(0, 1, 20)
print(array)
print("12 to 25 3*4 matrix")
array = np.arange(1, 26).reshape(5, 5)
print(array)
print("Result 1: ")
print(array[2:, 1:])
print("Result as 20")
print(array[3:4, 4:])
print(array[3, 4])
print("Result 3")
print(array[0:3, 1:2])
print("Result 4")
print(array[4, 0:])
# As 4 is the last row
print(array[-1, :])
print("Result 5")
print(array[3:, 0:])
print("Sum of all value")
print(array.sum())
print("Standard deviation")
print(np.std(array))
print(array.std())
print("Sum of all columns")
print(array.sum(axis=0))
print(("Sum of all rows"))
print(array.sum(axis=1))
